# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e0051032e0acb27cc4e31d1d187d500bf00a076d9c4a7c68ea0c18f9f835c0973761178b979d87d0b66433158f1983f1451c7dc5ab48f7a416f90d051209475

test:
  secret_key_base: d65f64211eec368fbd4bcf50278042c8873cc65874450e7a8bcb23c61c06473f007490cee143cf7eab166ab345d1fd2248b8fa7a6365af19499545a006cd7be4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
